### ISSUE TITLE
Heap Memory and Performance Issue

### ISSUE THREAD

**Issue by 0bp** [mschneider82/logstash-output-nsq#1] opened 2017-02-22 16:59 UTC
We're seeing a lot of heap memory consumption when the nsq output is enabled. Once the JVM HEAP is full the performance decreases to almost no messages are being processed.

Config:
```
input {
    generator {
    }
}
output {
   nsq {
        nsqlookupd => ["XXX.XXX.XXX.XXX:4161"]
        topic => "XXXX"
   }
}
```

- Logstash 5.2.1
- Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
- Debian Jessie

**Comment by mschneider82** [comment] 2017-02-22 17:11
does this also happen when using a static nsqd server on localhost?

```
output {
   nsq {
        nsqd => 127.0.0.1:4150"
        topic => "testtopic"
   }
}
```

**Comment by 0bp** [comment] 2017-02-22 17:16
Just tested, yes, same behaviour.

**Comment by mschneider82** [comment] 2017-02-23 13:17
I cannot verify this. 
Do you have a nsq consumer running? e.g.` ./nsq_tail --topic testgen --nsqd-tcp-address localhost:4150`
If you dont have a nsq consumer the nsqd will queue all messages to disk (only 10.000 msgs in memory).

Please provide more information about your testsetup

**Comment by 0bp** [comment] 2017-02-27 20:42
At the moment no consumers, just for some minutes for testing purposes. The counter says new messages incoming at a good rate even with no consumers. 

When heap memory gets full the incoming message rate drops drastically.

**Comment by mschneider82** [comment] 2017-03-06 13:29
can you please paste the output of:

`ls -l /usr/share/logstash/vendor/bundle/jruby/1.9/gems/ |grep nsq-ruby`

maybe its solved with nsq-ruby-2.0.5

**Comment by 0bp** [comment] 2017-03-06 15:14
```
# ls -l /usr/share/logstash/vendor/bundle/jruby/1.9/gems/ |grep nsq-ruby
drwxr-xr-x  3 logstash logstash 4096 Feb 21 10:20 nsq-ruby-2.0.5
``` 

I've re-installed logstash and jruby and now instead of getting very slow when heap memory is full, it seems to start a new thread that rises the heap memory.

![logstash-nsq](https://cloud.githubusercontent.com/assets/586405/23615775/d545ca20-0287-11e7-9ce4-0075c666ffd0.png)

Without output-nsq the heap memory stays at one level all the time. Heap is limited to 16 GB at the moment.

**Comment by mschneider82** [comment] 2017-03-06 15:25
If the input is faster then the output logstash will queue in memory. Using `generator { }` is a very performant input. on the other side `nsqd` will write to disk (after 10.000 messages) because you don't have a consumer on that topic, this will slow down `nsqd`. maybe you can use `pipeline.output.workers:` in `logstash.yml` to get more output workers, but generating is always faster then writing to disk.

**Comment by tanji** [comment] 2017-11-10 15:28
We're having the exact same issue with real data, and the consumer on the topic doesn't have anything in the queue. The heap just grows and when it reaches -Xmx (16G) the GC starts to freak out. You can see some metrics here: https://snapshot.raintank.io/dashboard/snapshot/Kq2GLnB65jc9eTbmZTELW4mipMvzqsn9?refresh=1m&orgId=2 
If you have any idea of what could cause this issue thanks for letting me know.

**Comment by mschneider82** [comment] 2017-11-14 16:24
@tanji I just noticed that there was a memory leak issue on nsq-ruby 2.0.0 fixed with 2.1.0, can you please check if this bug still happens by upgrading to the latest lib?

**Comment by tanji** [comment] 2017-11-17 11:29
Hi @mschneider82 unfortunately with nsq-ruby 2.1.0 it still leaks memory. The issue is I can't even record a java heap dump, it will refuse to do so I guess because of jruby.

**Comment by mschneider82** [comment] 2017-11-17 16:02
@tanji do you use filters?

I cannot reproduce this, my setup: (stable 7.9% memory of my system, not growing, default: -Xmx1g -Xms1g -Xss2048k)

**logstash.conf:**
```
input {
    generator {
    }
}

output {
   nsq {
        nsqd => "10.2.8.2:4150"
        topic => "test#ephemeral"
   }
}
```


**Dockerfile:**

```
FROM docker.elastic.co/logstash/logstash-oss:6.0.0
RUN /usr/share/logstash/bin/logstash-plugin install logstash-output-nsq
COPY logstash.conf /usr/share/logstash/pipeline/logstash.conf
```

**Comment by mschneider82** [comment] 2017-11-17 16:09
You can also watch the logstash statistics (if enabled in logstash.yml) to see whats going on
```
curl -XGET 'localhost:9600/_node/stats/jvm?pretty'
curl -XGET 'localhost:9600/_node/hot_threads?pretty'
```

**Comment by mschneider82** [comment] 2017-11-17 16:13
Using the docker image also set's some interessting java settings like `-XX:+HeapDumpOnOutOfMemoryError`

maybe you can try this to get a heapdump.

**Comment by mschneider82** [comment] 2017-11-20 16:25
@tanji Please test & report with my latest version 1.0.10, i did some performance tweaks

**Comment by mschneider82** [comment] 2017-11-21 10:37
I finally can reproduce this bug, using logstash (with jruby) and also with ruby. 
I opened issue https://github.com/wistia/nsq-ruby/issues/41

**Comment by tanji** [comment] 2017-11-21 11:04
Thanks a lot. I've upgraded to 1.0.10 but I'm still on a restart schedule to free up memory.

**Comment by tanji** [comment] 2017-11-21 19:24
@mschneider82 I don't want to interfere in the conversation upstream so I'm posting that here.

The memory usage we're seeing is happening with 100 events per second in input and output. With `generator` I understand that you're saturating the queue, however that is not at all what we experience.

**Comment by mschneider82** [comment] 2017-11-21 19:44
@tanji you could test my both fix solutions by removing the cache gems and hot fixing the connection.rb file (should work in theory - you can check if the hot patch works if you do some syntax errors, then logstash should not start...)

1. solution:
replace in line 113 the `write `with `write_to_socket`
2. solution:
try this: https://github.com/mschneider82/nsq-ruby/commit/f4ea585333129da17002c49cac0568e7c1154894

Please report what solution works better for you

**Comment by mschneider82** [comment] 2017-11-21 20:06
It should even works with `generator`. Since I dont use a own queue in my logstash plugin, it cannot allocate so much memory, it must be somewhere in the used library. To debug this we have do run plain ruby code to reproduce the problem.

**Comment by mschneider82** [comment] 2017-11-22 11:15
@tanji I still get memory `heap_used_percent: 98 `after processing 3.000.000 messages even with my patch. 

But i can now exclude the`nsq-ruby` libary because after my patch the loop.rb can now process 30.000.000 messages without a big memory usage.

So i played with some logstash config: Can you please try to set `codec` to `plain`, this solved the issue for me. It seems there is a bug with the `codec => json` in `logstash` or in my `implementation`

```
output {
  nsq {
    codec => plain
    nsqd => "10.0.0.1:4150"
    topic => "test#ephemeral"
  }
}
```

**Comment by mschneider82** [comment] 2017-11-22 14:35
@tanji please update to 1.0.11, I think its fixed now (even for `codec json`)!

**Comment by tanji** [comment] 2017-11-22 17:06
Hi @mschneider82,

`bin/logstash-plugin install logstash-output-nsq` stays on the 1.0.10. Have you upgraded the gem yet?

NB. Never mind it, had to use `update`. Duh. Will keep you posted about the stability!

**Comment by mschneider82** [comment] 2017-11-22 17:08
its updated see: https://rubygems.org/gems/logstash-output-nsq

**Comment by tanji** [comment] 2017-11-22 18:11
I am happy to say that the problem is fixed! Heap has been stable for 1hr. Thank you very much for your work!

**Closed as completed** 2017-11-22 19:15 UTC

**Comment by mschneider82** [comment] 2017-11-23 08:36
Just pushed version 2.0.0 with nsq-ruby 2.2.0, this includes patch for the Queue bottleneck
@0bp this fixes generator throughput.

**Comment by 0bp** [comment] 2017-11-23 10:44
Thanks a lot!
